# Generated by Django 5.2.4 on 2025-08-03 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('highschool', 'High School'), ('bachelor', "Bachelor's"), ('master', "Master's"), ('phd', 'PhD'), ('other', 'Other')], max_length=20, null=True)),
                ('preferred_field', models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('medicine', 'Medicine'), ('law', 'Law'), ('arts', 'Arts'), ('commerce', 'Commerce')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
