# Generated by Django 5.1.3 on 2026-05-21 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0004_emailverification_userprofile_email_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_role', models.CharField(max_length=140)),
                ('summary', models.TextField(blank=True)),
                ('current_level', models.CharField(default='beginner', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('assessment_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_roadmap', to='website.assessmentresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('focus', models.TextField()),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='roadmap.careerroadmap')),
            ],
            options={
                'ordering': ['month_number'],
                'unique_together': {('roadmap', 'month_number')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.PositiveIntegerField(default=0)),
                ('learning_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('projects_completed', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('roadmap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='roadmap.careerroadmap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User progress',
            },
        ),
        migrations.CreateModel(
            name='WeeklyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('learn', 'Learning'), ('project', 'Project'), ('certification', 'Certification'), ('internship', 'Internship Prep'), ('resume', 'Resume')], default='learn', max_length=24)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='roadmap.roadmapmonth')),
            ],
            options={
                'ordering': ['month__month_number', 'week_number', 'id'],
            },
        ),
    ]
