QUESTION_SETS = {
    "Business & Management": [
        "I enjoy coordinating people and moving projects toward clear goals.",
        "I am comfortable making decisions that affect a team or business outcome.",
        "I like improving workflows, productivity, and team performance.",
        "I can balance deadlines, people needs, and changing priorities.",
        "I am interested in leadership, operations, and strategy.",
    ],
    "Data & Analytics": [
        "I enjoy finding patterns in numbers, reports, or dashboards.",
        "I like turning raw information into useful insights.",
        "I am patient when cleaning, organizing, or checking data.",
        "I trust evidence and measurement when making decisions.",
        "I am interested in statistics, business intelligence, or forecasting.",
    ],
    "Design & Arts": [
        "I enjoy transforming abstract ideas into visuals or experiences.",
        "I care about aesthetics, storytelling, and emotional impact.",
        "I like iterating on creative work until it feels polished.",
        "I pay attention to layout, color, and user experience.",
        "I am interested in design, media, or visual communication.",
    ],
    "Engineering & Technology": [
        "I enjoy building systems, products, or technical solutions.",
        "I like understanding how tools and technologies work underneath.",
        "I am comfortable solving complex logical problems step by step.",
        "I enjoy improving performance, efficiency, or reliability.",
        "I am interested in engineering, software, or product development.",
    ],
    "Entrepreneurship & Innovation": [
        "I often notice opportunities where something could be built or improved.",
        "I like testing bold ideas even when the outcome is uncertain.",
        "I think about customers, markets, and value creation.",
        "I enjoy taking initiative and ownership over new ventures.",
        "I am interested in startups, innovation, or launching products.",
    ],
    "Environmental Sciences": [
        "I care about sustainability, ecology, and long-term environmental impact.",
        "I enjoy fieldwork, observation, or studying natural systems.",
        "I like solving real-world problems related to climate or conservation.",
        "I am interested in scientific approaches to environmental protection.",
        "I can see myself working on nature-focused research or policy.",
    ],
    "Finance & Banking": [
        "I enjoy working with budgets, financial planning, or performance metrics.",
        "I like making decisions based on numbers, risk, and return.",
        "I pay attention to trends in markets, business, or investments.",
        "I enjoy building structured plans around money and resources.",
        "I am interested in finance, banking, or financial analysis.",
    ],
    "Healthcare": [
        "I am motivated by helping people improve their health and quality of life.",
        "I stay calm when responsibility and precision matter.",
        "I can handle demanding work that requires empathy and discipline.",
        "I am interested in patient care, health systems, or medical support.",
        "I can see myself in a role that directly benefits people's wellbeing.",
    ],
    "IT & Cybersecurity": [
        "I enjoy understanding digital systems, networks, and security risks.",
        "I like troubleshooting technical issues methodically.",
        "I am alert to vulnerabilities, privacy, and system reliability.",
        "I enjoy protecting systems or users from digital threats.",
        "I am interested in IT infrastructure, security, or support engineering.",
    ],
    "Law & Political Science": [
        "I care about justice, public systems, and how rules shape society.",
        "I enjoy analyzing arguments, policies, and legal reasoning.",
        "I am comfortable debating ideas and defending a position.",
        "I like following current affairs, governance, or legal developments.",
        "I am interested in law, policy, or public affairs careers.",
    ],
    "Media and Communication": [
        "I enjoy shaping messages for audiences through writing, speaking, or media.",
        "I like understanding what captures attention and builds engagement.",
        "I am confident sharing ideas publicly or presenting clearly.",
        "I enjoy storytelling across digital, visual, or spoken formats.",
        "I am interested in communication, branding, or media strategy.",
    ],
    "Psychology & Social Work": [
        "I care deeply about emotional wellbeing and human development.",
        "I listen carefully and try to understand what people are feeling.",
        "I want work that supports people during challenges or change.",
        "I am interested in behavior, counseling, or community support.",
        "I can see myself helping individuals or groups in meaningful ways.",
    ],
    "Science & Research": [
        "I enjoy investigating how things work through evidence and experimentation.",
        "I like asking questions that require careful study and analysis.",
        "I am patient with detailed observation, testing, and documentation.",
        "I am interested in discovery, experimentation, or technical research.",
        "I can see myself contributing to scientific knowledge or innovation.",
    ],
    "Sports & Physical Wellness": [
        "I value physical performance, health habits, and active lifestyles.",
        "I enjoy coaching, motivating, or training people physically.",
        "I like work that is energetic, hands-on, and movement-focused.",
        "I am interested in sports, wellness, or physical conditioning.",
        "I can see myself helping others improve strength, fitness, or recovery.",
    ],
    "Teaching & Education": [
        "I enjoy helping people learn and understand difficult topics.",
        "I feel fulfilled when I explain ideas clearly and see progress.",
        "I can be patient, encouraging, and structured when guiding others.",
        "I like creating materials, lessons, or learning activities.",
        "I am interested in education, training, or instructional work.",
    ],
    "Writing & Literature": [
        "I enjoy expressing ideas through writing and careful word choice.",
        "I like reading deeply and analyzing tone, structure, or meaning.",
        "I pay attention to clarity, voice, and storytelling quality.",
        "I enjoy editing and refining written work until it feels strong.",
        "I am interested in writing, literature, or editorial careers.",
    ],
}


CAREER_RESULTS = {
    "Business & Management": {
        "career": "Business Operations Manager",
        "description": "Business operations managers improve processes, coordinate teams, and help organizations run effectively.",
        "salary": "Competitive role with strong growth across industries",
        "outlook": "Good long-term demand in business operations",
        "facts_source": "Career profile guidance",
        "sources": [
            {"title": "Project Management Institute", "url": "https://www.pmi.org/about/learn-about-pmi/what-is-project-management", "type": "Field overview"},
            {"title": "Harvard Business Review", "url": "https://hbr.org/", "type": "Management learning"},
            {"title": "Coursera Business Foundations", "url": "https://www.coursera.org/browse/business", "type": "Learning path"},
        ],
    },
    "Data & Analytics": {
        "career": "Data Scientist",
        "description": "Data scientists use statistics, programming, and machine learning to turn data into predictions, insights, and better decisions.",
        "salary": "Strong demand in analytics-focused roles",
        "outlook": "Growing need for data-driven decision making",
        "facts_source": "Career profile guidance",
        "sources": [
            {"title": "Google Data Analytics Certificate", "url": "https://www.coursera.org/professional-certificates/google-data-analytics", "type": "Learning path"},
            {"title": "Kaggle Learn", "url": "https://www.kaggle.com/learn", "type": "Practice"},
            {"title": "IBM Data Analyst Career Guide", "url": "https://www.ibm.com/think/topics/data-analyst", "type": "Role details"},
        ],
    },
    "Design & Arts": {
        "career": "UI/UX Designer",
        "description": "UI/UX designers research needs, structure interfaces, and craft digital experiences that feel clear, useful, and visually polished.",
        "salary": "$98,090 median annual pay",
        "outlook": "7% projected growth (2024-2034)",
        "facts_source": "U.S. Bureau of Labor Statistics",
        "sources": [
            {"title": "Occupational Outlook: Web and Digital Interface Designers", "url": "https://www.bls.gov/ooh/computer-and-information-technology/web-developers.htm", "type": "Career outlook"},
            {"title": "Google UX Design Certificate", "url": "https://www.coursera.org/professional-certificates/google-ux-design", "type": "Learning path"},
            {"title": "O*NET: Web and Digital Interface Designers", "url": "https://www.onetonline.org/link/summary/15-1255.00", "type": "Role details"},
        ],
    },
    "Engineering & Technology": {
        "career": "Software Engineer",
        "description": "Software engineers design, build, and maintain applications and systems used by real people and businesses.",
        "salary": "$133,080 median annual pay",
        "outlook": "15% projected growth (2024-2034)",
        "facts_source": "U.S. Bureau of Labor Statistics",
        "sources": [
            {"title": "Occupational Outlook: Software Developers", "url": "https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm", "type": "Career outlook"},
            {"title": "MDN Learn Web Development", "url": "https://developer.mozilla.org/en-US/docs/Learn", "type": "Skill building"},
            {"title": "O*NET: Software Developers", "url": "https://www.onetonline.org/link/summary/15-1252.00", "type": "Role details"},
        ],
    },
    "Entrepreneurship & Innovation": {
        "career": "Startup Founder",
        "description": "Entrepreneurs identify opportunities, test new ideas, and build products or businesses around real market needs.",
        "salary": "Varies widely by business stage and market",
        "outlook": "Opportunity-driven career path",
        "facts_source": "Startup and business learning resources",
        "sources": [
            {"title": "Y Combinator Startup Library", "url": "https://www.ycombinator.com/library", "type": "Startup learning"},
            {"title": "Entrepreneur Startup Guide", "url": "https://www.entrepreneur.com/starting-a-business", "type": "Field overview"},
            {"title": "Coursera Entrepreneurship", "url": "https://www.coursera.org/browse/business/entrepreneurship", "type": "Learning path"},
        ],
    },
    "Environmental Sciences": {
        "career": "Environmental Scientist",
        "description": "Environmental scientists study ecosystems, assess impact, and help organizations make more sustainable decisions.",
        "salary": "Specialized science role with public and private sector demand",
        "outlook": "Steady need in sustainability and compliance work",
        "facts_source": "Environmental career resources",
        "sources": [
            {"title": "EPA Environmental Information", "url": "https://www.epa.gov/environmental-topics", "type": "Field overview"},
            {"title": "National Geographic Environment", "url": "https://www.nationalgeographic.com/environment", "type": "Topic exploration"},
            {"title": "Coursera Environmental Science", "url": "https://www.coursera.org/courses?query=environmental%20science", "type": "Learning path"},
        ],
    },
    "Finance & Banking": {
        "career": "Financial Analyst",
        "description": "Financial analysts evaluate numbers, market trends, and business performance to guide planning and investment decisions.",
        "salary": "Strong compensation in finance and banking tracks",
        "outlook": "Consistent demand in financial planning and analysis",
        "facts_source": "Finance career resources",
        "sources": [
            {"title": "Investopedia Financial Analyst Guide", "url": "https://www.investopedia.com/articles/financialcareers/08/financial-analyst-job.asp", "type": "Role details"},
            {"title": "Corporate Finance Institute", "url": "https://corporatefinanceinstitute.com/", "type": "Skill building"},
            {"title": "Coursera Finance Courses", "url": "https://www.coursera.org/browse/business/finance", "type": "Learning path"},
        ],
    },
    "Healthcare": {
        "career": "Healthcare Professional",
        "description": "Healthcare careers combine clinical knowledge, responsibility, and compassion to improve patient outcomes and wellbeing.",
        "salary": "Varies by specialization and qualification level",
        "outlook": "Strong demand across healthcare systems",
        "facts_source": "Healthcare career resources",
        "sources": [
            {"title": "MedlinePlus Health Topics", "url": "https://medlineplus.gov/healthtopics.html", "type": "Field overview"},
            {"title": "NIH Health Information", "url": "https://www.nih.gov/health-information", "type": "Trusted source"},
            {"title": "Coursera Healthcare Courses", "url": "https://www.coursera.org/browse/health", "type": "Learning path"},
        ],
    },
    "IT & Cybersecurity": {
        "career": "Cybersecurity Analyst",
        "description": "Cybersecurity analysts protect systems, data, and users by identifying risks and improving security controls.",
        "salary": "High-demand technology security role",
        "outlook": "Growing demand as security risks increase",
        "facts_source": "Cybersecurity career resources",
        "sources": [
            {"title": "CISA Cyber Resource Hub", "url": "https://www.cisa.gov/resources-tools/resources", "type": "Trusted source"},
            {"title": "Cisco Networking Academy Cybersecurity", "url": "https://www.netacad.com/courses/cybersecurity", "type": "Learning path"},
            {"title": "O*NET Cybersecurity Roles", "url": "https://www.onetonline.org/find/quick?s=cybersecurity", "type": "Role details"},
        ],
    },
    "Law & Political Science": {
        "career": "Corporate Lawyer",
        "description": "Law and policy careers focus on justice, regulation, legal reasoning, governance, and public decision making.",
        "salary": "$151,160 median annual pay",
        "outlook": "5% projected growth (2024-2034)",
        "facts_source": "U.S. Bureau of Labor Statistics",
        "sources": [
            {"title": "Occupational Outlook: Lawyers", "url": "https://www.bls.gov/ooh/legal/lawyers.htm", "type": "Career outlook"},
            {"title": "LSAC Discover Law", "url": "https://www.lsac.org/discover-law", "type": "Career path"},
            {"title": "ABA Career Resources", "url": "https://www.americanbar.org/groups/law_students/career-resources/", "type": "Professional resources"},
        ],
    },
    "Media and Communication": {
        "career": "Communication Specialist",
        "description": "Communication specialists shape messages, campaigns, and content for audiences across digital and public channels.",
        "salary": "Strong opportunities across media, PR, and brand teams",
        "outlook": "Healthy demand in digital communication roles",
        "facts_source": "Communication career resources",
        "sources": [
            {"title": "HubSpot Marketing and Content Resources", "url": "https://blog.hubspot.com/marketing", "type": "Skill building"},
            {"title": "Google Digital Garage", "url": "https://learndigital.withgoogle.com/digitalgarage", "type": "Learning path"},
            {"title": "Coursera Communication Courses", "url": "https://www.coursera.org/courses?query=communication", "type": "Learning path"},
        ],
    },
    "Psychology & Social Work": {
        "career": "Counselor",
        "description": "Counseling and social support careers focus on wellbeing, guidance, empathy, and helping people through change.",
        "salary": "Meaningful people-centered career path",
        "outlook": "Continued need in mental health and support services",
        "facts_source": "Psychology and social work learning resources",
        "sources": [
            {"title": "American Psychological Association", "url": "https://www.apa.org/", "type": "Trusted source"},
            {"title": "National Association of Social Workers", "url": "https://www.socialworkers.org/", "type": "Professional resource"},
            {"title": "Coursera Psychology Courses", "url": "https://www.coursera.org/browse/social-sciences/psychology", "type": "Learning path"},
        ],
    },
    "Science & Research": {
        "career": "Research Scientist",
        "description": "Research scientists investigate questions systematically, analyze evidence, and contribute new knowledge or technical discoveries.",
        "salary": "Specialized role depending on domain and education level",
        "outlook": "Steady opportunities in labs, academia, and industry",
        "facts_source": "Science learning resources",
        "sources": [
            {"title": "Nature Careers", "url": "https://www.nature.com/naturecareers", "type": "Career resource"},
            {"title": "National Science Foundation", "url": "https://new.nsf.gov/", "type": "Trusted source"},
            {"title": "Coursera Research Methods", "url": "https://www.coursera.org/courses?query=research%20methods", "type": "Learning path"},
        ],
    },
    "Sports & Physical Wellness": {
        "career": "Fitness Coach",
        "description": "Sports and wellness roles help people improve performance, health habits, movement, and physical conditioning.",
        "salary": "Varies by specialization and client base",
        "outlook": "Strong interest in fitness and preventive wellness",
        "facts_source": "Sports and wellness learning resources",
        "sources": [
            {"title": "ACSM Career Resources", "url": "https://www.acsm.org/certification", "type": "Professional resource"},
            {"title": "NASM Fitness Careers", "url": "https://www.nasm.org/", "type": "Learning path"},
            {"title": "Coursera Health and Fitness Courses", "url": "https://www.coursera.org/courses?query=fitness", "type": "Learning path"},
        ],
    },
    "Teaching & Education": {
        "career": "Educator",
        "description": "Educators design learning experiences, explain ideas clearly, and support student growth over time.",
        "salary": "Stable career path with many subject specializations",
        "outlook": "Consistent demand in schools and training settings",
        "facts_source": "Education career resources",
        "sources": [
            {"title": "Edutopia", "url": "https://www.edutopia.org/", "type": "Teaching practice"},
            {"title": "Khan Academy", "url": "https://www.khanacademy.org/", "type": "Learning resource"},
            {"title": "Coursera Education Courses", "url": "https://www.coursera.org/browse/education", "type": "Learning path"},
        ],
    },
    "Writing & Literature": {
        "career": "Content Writer",
        "description": "Writing careers center on clarity, narrative, analysis, and shaping ideas for readers across formats.",
        "salary": "Flexible path across editorial, content, and publishing work",
        "outlook": "Strong opportunities in digital content and editorial roles",
        "facts_source": "Writing and editorial resources",
        "sources": [
            {"title": "Purdue OWL Writing Resources", "url": "https://owl.purdue.edu/", "type": "Skill building"},
            {"title": "MasterClass Writing Articles", "url": "https://www.masterclass.com/categories/writing", "type": "Creative learning"},
            {"title": "Coursera Writing Courses", "url": "https://www.coursera.org/courses?query=writing", "type": "Learning path"},
        ],
    },
}
