# Generated by Django 5.1.3 on 2026-05-21 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('company', models.CharField(max_length=160)),
                ('opportunity_type', models.CharField(choices=[('internship', 'Internship'), ('job', 'Fresher Job'), ('remote', 'Remote Job')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('remote', models.BooleanField(default=False)),
                ('source_url', models.URLField(blank=True)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_match_percentage', models.PositiveIntegerField(default=0)),
                ('resume_match_percentage', models.PositiveIntegerField(default=0)),
                ('overall_match_percentage', models.PositiveIntegerField(default=0)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.opportunity')),
            ],
            options={
                'ordering': ['-overall_match_percentage'],
                'unique_together': {('user', 'opportunity')},
            },
        ),
    ]
